coverage:
  status:
    project:
      default:
        base: auto
        branches:
          - main
        flags:
          - unit
        if_ci_failed: error
        informational: false
        only_pulls: false
        paths:
          - lib
        target: 60%
        threshold: 10%
    patch:
      target: 60%
      threshold: 5%
      paths:
        - lib
  ignore:
    - "lib/main.dart"
    - "lib/gen"
    - "lib/features/debug"
    - "lib/initial_app.dart"
    - "lib/route/**"
    - "lib/singleton"
    - "lib/strings"
    - "lib/data"
    - "lib/l10n"
    - "lib/**/*_event.dart"
    - "lib/**/*_state.dart"