coverage:
  status:
    project:
      default:
        base: auto
        branches:
          - main
        flags:
          - unit
        if_ci_failed: error
        informational: false
        only_pulls: false
        paths:
          - lib
        target: auto
        threshold: 60%
ignore:
  - "lib/main.dart"
  - "lib/gen"
  - "lib/services"