coverage:
  status:
    project:
      default:
        base: auto
        branches:
          - main
        flags:
          - unit
        if_ci_failed: error
        informational: false
        only_pulls: false
        paths:
          - lib
        target: 60%
        threshold: 3%
  ignore:
    - "lib/main.dart"
    - "lib/gen"
    - "lib/features/debug"
    - "lib/initial_app.dart"
    - "lib/route/**"