// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE5F0QBXf8CGMDdDlBR2ekK0LtmuPoUX8',
    appId: '1:8474379889:web:80f9d711dae0f661bbfdd0',
    messagingSenderId: '8474379889',
    projectId: 'auth-flutter-test-d3a5a',
    authDomain: 'auth-flutter-test-d3a5a.firebaseapp.com',
    storageBucket: 'auth-flutter-test-d3a5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDBEW5klgondSEp0kxwNOgTSBNWF4MFi8',
    appId: '1:8474379889:android:183669eec897bccdbbfdd0',
    messagingSenderId: '8474379889',
    projectId: 'auth-flutter-test-d3a5a',
    storageBucket: 'auth-flutter-test-d3a5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOfy2psEJ_RI0DcvcAIa9scMgtex6cDKA',
    appId: '1:8474379889:ios:5f85cdcd06a0becbbbfdd0',
    messagingSenderId: '8474379889',
    projectId: 'auth-flutter-test-d3a5a',
    storageBucket: 'auth-flutter-test-d3a5a.appspot.com',
    iosClientId: '8474379889-oh1chpvsl8p5fmqncqq5j1eaflb3f6ij.apps.googleusercontent.com',
    iosBundleId: 'com.theseedsoft.hatspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOfy2psEJ_RI0DcvcAIa9scMgtex6cDKA',
    appId: '1:8474379889:ios:d84dccfa5549c659bbfdd0',
    messagingSenderId: '8474379889',
    projectId: 'auth-flutter-test-d3a5a',
    storageBucket: 'auth-flutter-test-d3a5a.appspot.com',
    iosClientId: '8474379889-qle57n0kcoqalqt7a0du0h9tuhdl2aaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hatspace',
  );
}
