// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMvucf5Ri7LwxJCV61jnSMG6P88BP8mE0',
    appId: '1:954705043647:web:220ea6188740457179a60a',
    messagingSenderId: '954705043647',
    projectId: 'registration-form-c8c90',
    authDomain: 'registration-form-c8c90.firebaseapp.com',
    databaseURL: 'https://registration-form-c8c90-default-rtdb.firebaseio.com',
    storageBucket: 'registration-form-c8c90.appspot.com',
    measurementId: 'G-SGY65FLZK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXle47ZhkyFFWNDQXeTZbHqlnO_hm4Tzw',
    appId: '1:954705043647:android:de2219cd4710494a79a60a',
    messagingSenderId: '954705043647',
    projectId: 'registration-form-c8c90',
    databaseURL: 'https://registration-form-c8c90-default-rtdb.firebaseio.com',
    storageBucket: 'registration-form-c8c90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8q2GajZsOh9kYvKMIuEL_1v7zj0PDgjU',
    appId: '1:954705043647:ios:3dc2adda3acf125579a60a',
    messagingSenderId: '954705043647',
    projectId: 'registration-form-c8c90',
    databaseURL: 'https://registration-form-c8c90-default-rtdb.firebaseio.com',
    storageBucket: 'registration-form-c8c90.appspot.com',
    iosClientId: '954705043647-jq2dj03skrgmdob7f6j470meffg63j58.apps.googleusercontent.com',
    iosBundleId: 'com.theseedsoft.hatspace',
  );
}
