# This is a basic workflow to help you get started with Actions

name: Build Android release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request on all branches, except "main" branch
  push:
    branches: 
    - 'HS-40-CICD'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_apk:
    name: Build Flutter (Android)
    # The type of runner that the job will run on
    runs-on: macos-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # install Java 11 to build Android app
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # use flutter-action to start running flutter commands
      - uses: subosito/flutter-action@v2.6.2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
       # env:
        #  KEY_JKS: ${{ secrets.RELEASE_KEYSTORE }}
        #  SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
        #  SIGNING_KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        #  SIGNING_STORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      
      - name: Setup environment secrets
        shell: bash
        env:
          FIREBASE_OPTION: ${{ secrets.FIREBASE_OPTION }}
          ANDROID_GOOGLE_SERVICE: ${{ secrets.ANDROID_GOOGLE_SERVICE }}
          FIREBASE_APP_ID_FILE: ${{ secrets.FIREBASE_APP_ID_FILE }}
          ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          
        run: |
          echo -n "$FIREBASE_OPTION" | base64 --decode --output lib/firebase_options.dart
          echo "$ANDROID_GOOGLE_SERVICE" | base64 --decode --output android/app/google-services.json
          echo "$FIREBASE_APP_ID_FILE" | base64 --decode --output ios/firebase_app_id_file.json
        # put keystore
          echo -n "$ANDROID_KEYSTORE" | base64 --decode --output android/key.jks  
        # put keyproperties
          echo "$ANDROID_KEY_PROPERTIES" | base64 --decode --output android/key.properties
      
      - name: Install dependencies
        shell: bash
        run: |
          flutter clean
          flutter pub get
          flutter pub run build_runner build
          flutter pub run intl_utils:generate

      # Runs a set of commands using the runners shell
      - name: Run test with coverage
        run: flutter test --coverage
        
      # Run codecov summary
      - uses: codecov/codecov-action@v3

      - name: build Android and iOS
        run: |
          flutter build apk
          
